### ISSUE TITLE
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

### ISSUE THREAD

**Issue by itsashis4u** [barthap/with-rn-firebase#3]
Thank you for this library. 

I tried it by following the steps mentioned in the Readme.
But I'm getting this error
```
Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()
```

Do we need to explicitly initialise the app ourselves?

**Comment by barthap** [comment]
Hello,

> Do we need to explicitly initialise the app ourselves?

No, if you're using [`react-native-firebase`](https://rnfirebase.io/), you shouldn't have to.

A few things to consider:

- Aren't you accidently importing the [`firebase`](https://www.npmjs.com/package/firebase) package? I mean the JS Web SDK. The error looks like it comes from that library. If yes, replace these calls with the react-native-firebase ones. My plugin isn't needed for the JS library.

- Are you trying to run this in Expo Go downloaded from Play/App Store? The config plugins aren't supported there.

- Which Expo SDK are you using? This plugin works only for SDK 41+.

- Are you trying on Android or iOS? What is your current workflow? How do you build and run your app?

**Comment by itsashis4u** [comment]
I think I screwed up somewhere.

> Aren't you accidently importing the firebase package? I mean the JS Web SDK. The error looks like it comes from that library. If yes, replace these calls with the react-native-firebase ones. My plugin isn't needed for the JS library.

I am importing react native firebase library
```
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-firebase/firestore": "^12.1.0",
```
--- 
> Are you trying to run this in Expo Go downloaded from Play/App Store? The config plugins aren't supported there.

I am using it with `expo run:ios` and `expo run:android` commands

---

> Which Expo SDK are you using? This plugin works only for SDK 41+.

I am using SDK 41
```
"expo": "~41.0.1",
```

CLI version
```
➜ expo --version
4.7.1
```
---

> Are you trying on Android or iOS? What is your current workflow? How do you build and run your app?

I am trying for both android and iOS. This error only comes up in case of iOS
To build my app I use `expo run:ios`

Also here is my `app.json` config
```
"plugins": [
      [
        "with-rn-firebase",
        {
          "androidGoogleServicesPath": "./config/google-services.json",
          "iosGoogleServicesPath": "./config/GoogleService-Info.plist"
        }
      ]
    ]
```

**Comment by itsashis4u** [comment]
Also I'm getting this warning when running `expo run:ios`

```
› Executing App » [CP-User] [RNFB] Core Configuration
      A firebase.json file was not found, whilst this file is optional it is recommended to include it to configure firebase services in React Native Firebase.
```

**Comment by barthap** [comment]
That warning is unrelated.

Please go into `ios/[yourappname]/AppDelegate.m` and check if it contains these lines:

-  
   ```objective-c
   @import Firebase
   ```
   somewhere at the beggining

- ```objective-c
     [FIRApp configure]
   ```
   somewhere in `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

If these lines are missing, the config plugin didn't work properly. In that case, please run `expo config --type prebuild` and paste the log here.

**Comment by itsashis4u** [comment]
my `AppDelegate.m` doesn't have the lines you mentioned

Here's the config
https://gist.github.com/itsashis4u/3b28aaab49de7caf116d3647868cc36c

**Comment by barthap** [comment]
I'm investigating it, but I cannot reproduce - the `AppDelegate.m` gets modified (these two lines are added) when I run `expo prebuild`.

The steps I'm doing:
```sh
expo init
yarn add @react-native-firebase/app ...
expo install with-rn-firebase
# put GoogleServices and set the paths in app.json
expo prebuild
```

The `prebuild` command is part of `expo run` - it builds your app but doesn't start it.

**Comment by itsashis4u** [comment]
Interestingly, I had never run `expo prebuild` before. 
I just used the `expo run` commands. But running `expo prebuild` added the following lines to my `AppDelegate.m` file

> @import Firebase
   [FIRApp configure]
somewhere in - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

Thank you for your help @barthap :)

**Comment by barthap** [comment]
Happy to help!

But that's interesting - afaik `expo run` should internally run the `prebuild`. It looks like it may be `expo-cli` internal bug. I'll investigate that further.
