### ISSUE TITLE
Crashlytics crashes Android on app start

### ISSUE THREAD

**Issue by dcanora** [barthap/with-rn-firebase#4]
First of all, thanks very much for this plug in!

I can run:ios in the simulator with no issue.  When I run:android - in simulator or on device - the app crashes before loading.  Looking at the logs, I see `The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.`

Crashlytics is enabled in Firebase.  I saw in the rnfirebase docs there is config required for Crashlytics. Is this supported by the plugin? Is there anything else I need to do?  TIA... 

Expo diagnostics...

  Expo CLI 4.7.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ^0.13.18 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.7.2
    Expo Workflow: bare   (<< I'm using managed workflow with `expo run`)

**Comment by barthap** [comment]
Hello, I haven't implemented the crashlytics configuration yet. For now, you have to do the steps from docs manually.

I'm going to implement this soon 😇

**Comment by dcanora** [comment]
Understood. Thanks for the quick reply, @barthap, and thanks again for the plug-in!

**Comment by barthap** [comment]
Hello again @dcanora!

I've published a pre-release with basic support for crashlytics, you can try it out:

- `yarn add with-rn-firebase@next`
- In `app.json` set the `androidOptions.installCrashlytics` to `true` in plugin settings. See [example in readme](https://github.com/barthap/with-rn-firebase#other-configuration-options)

**Edit:** It's now fully released in `0.3.0`

**Comment by dcanora** [comment]
@barthap FYI - I just rebuilt (using `expo run:android -d`) to try it out. Seems to work fine. Thanks!
